services:
- type: pserv
  name: mariadb
  plan: standard
  env: docker
  disk:
    name: mariadb
    mountPath: /var/lib/mysql
    sizeGB: 10
  envVars:
  - fromGroup: mariadb

envVarGroups:
- name: mariadb
  envVars:
  - key: MYSQL_DATABASE
    value: mariadb
  - key: MYSQL_USER
    value: mariadb
  - key: MYSQL_PASSWORD
    generateValue: true
  - key: MYSQL_ROOT_PASSWORD
    generateValue: true
